baseURL = ''
languageCode = 'en-us'
title = 'Twitter Downfall'
theme = 'pixyll'

builddrafts = false

contentdir = "content"
publishdir = "public"
canonifyurls = true

[indexes]
category = "categories"
tag = "tags"

[params]
search_engine = true
